---
title: "Hector V 3.5"
author: "Kalyn Dorheim"
date: today
toc: true
format:
  html:
    html-math-method: katex
    code-tools: true
    self-contained: true
execute:
  warning: false
  message: false
  echo: false
---

# Objective

Comparison of hector V 3.5.0 with available magicc & fair results (RCMIP I).


```{r, echo = FALSE}
library(dplyr)
library(ggplot2)
library(hector)
library(tidyr)
theme_set(theme_bw())

# TODO this will need to be updated to reflect the project location
BASE_DIR <- "/Users/dorh012/Documents/Hector-WD/hector_benchmarking"
```

```{r}
```


```{r}
```

```{r}
file.path(BASE_DIR, "data", "hector_magicc.csv") %>% 
  read.csv ->
  magicc_data

file.path(BASE_DIR, "data", "hector_fair.csv") %>% 
  read.csv ->
  fair_data

magicc_data %>%  
  rbind(fair_data) %>%  
  filter(year %in% 1900:2100) %>% 
  filter(variable == GLOBAL_TAS()) -> 
  rslts
```

# Comparison

```{r, fig.align='center'}
rslts %>% 
  ggplot(aes(year, value, color = model)) + 
  geom_line() + 
  facet_wrap("scenario", scales = "free") + 
  labs(y = "temp anomoly relative 1850-1900 (deg C)", 
       title = GLOBAL_TAS(), 
       x = NULL)
```


```{r, echo = FALSE}
rslts %>% 
  filter(model == "hector 3.5.0") %>% 
  select(year, variable, hector = value, scenario) %>% 
  distinct -> 
  hector_rslts


rslts %>% 
  filter(model != "hector 3.5.0") %>% 
  select(-units) %>% 
  left_join(hector_rslts, by = join_by(scenario, variable, year)) %>% 
  mutate(scenario = if_else(year < 2015, "historical", scenario)) %>% 
  #filter(scenario != "historical") %>% 
  na.omit %>% 
  mutate(diff = hector - value) -> 
  diff_table
```

The mean difference between hector and model temp.   

```{r, echo = FALSE}  
  diff_table %>% 
  summarise(value = mean(diff), .by = c(scenario, model)) %>% 
  knitr::kable(digits = 3)
```

Difference between 2100 hector and model temp.

```{r, echo = FALSE}  
diff_table %>% 
  filter(year == 2100) %>% 
  knitr::kable(digits = 3)
```


